### ISSUE TITLE
Add documentation on how to use the FreqSort with Advanced Browser

### ISSUE THREAD

**Issue by St0wy** [donkuri/lapis#15]
The readme says :

> Lapis uses harmonic frequency ranking to create a FreqSort field you can use to re-order your new cards by frequency, either manually by using [Advanced Browser](https://ankiweb.net/shared/info/874215009)

But after looking at the addon documentation and looking around in the app, I haven't found any way to do this

PS : Thanks a lot for this note type, it's amazing !

**Comment by bewizible** [comment]
Hmmmm... I think this might be worth it, @donkuri what are your thoughts?

**Comment by mcgrizzz** [comment]
Just did some minor digging. Here's how you can do this with the Advanced Browser addon.

1. Go into the browser and limit the search to new cards (so you do not affect already reviewed/learned cards). Something like `deck:Mining is:new` should be in your search bar depending on what your mining deck is called. 

![image](https://github.com/user-attachments/assets/d8675320-ea19-464a-bf44-ba96a4b44992)

2. Right Click on the headers and go to

**Comment by donkuri** [comment]
I feel like this isn't quite directly related to Lapis so I have mixed feelings on this one. Maybe we just link to this issue instead, since @mcgrizzz wrote a nice guide?

**Comment by St0wy** [comment]
Why not copy the guide in a Markdown file in the docs folder and link to it in the readme ? Doesn't really clutter the base informations and that way it can be updated. But yeah linking to this issue is also a good solution :)

**Comment by donkuri** [comment]
Yeah that's an even better idea, let me do that.

**Comment by mcgrizzz** [comment]
> Yeah that's an even better idea, let me do that. @mcgrizzz Is that okay with you? I will credit you of course.

Of course, go ahead.

**Comment by donkuri** [comment]
Done in the latest commit. Thanks everyone!
