### ISSUE TITLE
Display sentence above definition on AnkiDroid

### ISSUE THREAD

**Issue by St0wy** [donkuri/lapis#16]
I'm not sure if this is due to an error in the configuration of the model, but on my phone, the sentences are displayed bellow the definition, but not on PC.

PC: 
![image](https://github.com/user-attachments/assets/91083658-40a2-4175-b068-94d0a60010a1)

Phone:
![Screenshot_20241121-101922 (Medium)](https://github.com/user-attachments/assets/8f90bf6e-369d-4a23-b6c8-c063f476aab6)

**Comment by bee-san** [comment]
![2024_11_21_16-02__cMU](https://github.com/user-attachments/assets/e75135b8-6905-4d2c-bcc4-6e4bf8ebf6fe)

On lightmode it uses this CSS, which sets it to this hex colour for bold. 

![2024_11_21_16-04__5Le](https://github.com/user-attachments/assets/4b8b9d6b-a87c-472a-9bd2-ab8b123235e9)

I manually changed the HTML to add the `<b>` tag, and it does apper bolded now.

I changed it to black and reset the bolding
![2024_11_21_16-05__MmA](https://github.com/user-attachments/assets/8ecc8f8e-191f-464f-84e5-8a2a9fc80410)

Again, `bold` is set to a specific hex colour but it obviously isn't bolded.

I tested this on IOS, and then installed Anki on a device with no addons and still get the same issue.

![2024_11_21_16-07__r5v](https://github.com/user-attachments/assets/5fb88244-7fed-4a55-af77-697abef611de)

Interestingly the HTML uses the same class for all of the terms, and does not indicate which term is the term we want to bold. I am not sure how you would auto-bold this in the code? 🤔 

It is bolded in Anki, and Anki probably passes that to your card template. But somewhere along the line, this boldness is removed :(

**Comment by bewizible** [comment]
This is delibrate and intended, as while developing this card I used a lot of JPMN as visual inspiration, and JPMN did it that way, hence we made this styling choice

**Comment by donkuri** [comment]
Mmmh, I feel like I agree with St0wy here. We should probably change this. @bewizible

**Comment by donkuri** [comment]
You can now follow [this section](https://github.com/donkuri/lapis?tab=readme-ov-file#how-can-i-move-the-sentence-on-mobile) in order to do this, thank you!
