### ISSUE TITLE
Are kana frequency in JPDB used for FreqSort calculation

### ISSUE THREAD

**Issue by Skretkowicz** [donkuri/lapis#25]
<img width="323" alt="image" src="https://github.com/user-attachments/assets/081b07b5-9c5d-4f15-89da-544cc67f629e" />

Something I've been wondering, if I have JPDB freq dicitonary, does the freqsort take the Kana reading into consideration when adding a word? it seems that it can skew the median pretty strongly so I am not sure should I keep it enabled

**Comment by donkuri** [comment]
This is probably not something that should be asked here but I will ask Marv since he would know.

**Comment by MarvNC** [comment]
Not if you're using JPDB v2.(latest) from Kuuube's repository.

**Comment by donkuri** [comment]
Linking it here just to make sure it's clear: https://github.com/Kuuuube/yomitan-dictionaries?tab=readme-ov-file#jpdb-v22-frequency

With this, I will close this issue. Thank you!
