### ISSUE TITLE
Take out the Jitendex/JMdict version date in the definitions

### ISSUE THREAD

**Issue by donkuri** [donkuri/lapis#26]
I find it pretty annoying that the JMdict/Jitendex version shows up in the definition and I wonder if there's a way to make that stop with some CSS/JS. For now, I'm using the following regex to take it out by using `Find and Replace` in Anki: `, JMdict \[\d{4}-\d{2}-\d{2}\]` (this is for JMdict, obviously).

**Comment by bewizible** [comment]
One fix you could use is edit the very zip itself, it's pretty easy

**Comment by donkuri** [comment]
I see, then maybe making a small note in the FAQ would work better. Thanks peeps!

**Comment by bewizible** [comment]
> You can actually rename your dictionaries directly in Yomitan ...

@itokatsu How?

**Comment by donkuri** [comment]
Ok, I will close this issue and mention your message in the readme then. Thanks!
