### ISSUE TITLE
Javascript indentation width

### ISSUE THREAD

**Issue by itokatsu** [donkuri/lapis#31]
Since it's an .html, most editors will make them 2-space wide. It makes sense for HTML, but the back is mostly Javascript, and it makes it kinda hard to read.
Can we agree to make them 4 wide on the whole file ? Or at least on the Javascript part.

**Comment by donkuri** [comment]
A picture here would be helpful. What is "an .html" here. Do you mean the front, back, both?

**Comment by donkuri** [comment]
Yeah, I agree. I think I like 4 as well. If you make a PR, I'll merge it.

**Comment by bewizible** [comment]
I'll fix this myself so no worries, just need to format the code
