### ISSUE TITLE
I can't find the mistake，that happen when I wanna take word in anki

### ISSUE THREAD

**Issue by keeptrykeep** [donkuri/lapis#32]
An error occurred:
Template render error for {frequency-harmonic-rank}
Log debug info to console
![f2184bcf074374422c1f0eb0c43d31a4](https://github.com/user-attachments/assets/2c5ed055-976c-4066-a73f-e12af33cb8ae)

**Comment by YonKuma** [comment]
Are you using an up to date version of Yomitan? This looks like an error that you would get if you were still using Yomichan.

**Comment by donkuri** [comment]
That is indeed a bug with Yomitan. Either you are using Yomichan or you are using an outdated version of Yomitan. We don't support either of these, so please do update.
