### ISSUE TITLE
Incomplete digraph detection

### ISSUE THREAD

**Issue by zeyonaut** [donkuri/lapis#33]
The generated pronunciation guide for ティー [1] is currently incorrect due  to `groupMoras` not accounting for ィ. This could (theoretically) also affect odaka detection and other small vowel kana occurring after, say, ヴ, but I'm not sure if there are any useful examples.

**Comment by donkuri** [comment]
This is a really good catch, thank you. @bewizible

**Comment by bewizible** [comment]
Could you give any examples on which I could test this @zeyonaut

**Comment by bewizible** [comment]
I think it's fixed, groupMoras() now accounts for ィ, thanks!
