### ISSUE TITLE
Hide the first line of SelectionText

### ISSUE THREAD

**Issue by JonLuepf** [donkuri/lapis#36]
I want to hide the first line of the SelectionText field to get rid of the dictionary name. In JPMN I can do it like this: https://arbyste.github.io/jp-mining-note/definitions/#ui-options

**Comment by bewizible** [comment]
`SelectionText` only contains what you _select_ per se, so don't select the dictionary name?

**Comment by bewizible** [comment]
And if you mean `MainDefintion` then sorry, it's Lapis's rule of sorts to not mess with dictionary css/rendering. Also JPMN uses it's own handlebars which have selectors allowing it to hide and show any part of the definition really, Lapis, using yomtan's vanilla handlebars, _can't_ do that. @donkuri thoughts?

**Comment by JonLuepf** [comment]
I followed the guide to convert my existing JPMN notes to Lapis notes. That results in my main definition being in the SelectionText field.

I guess since Lapis just uses the Yomitan handlebars I should raise these issues with the Yomitan developers instead maybe? I also would want to have the option to have mined cards with no frequency have a frequency of 0 instead of 99999 if possible which was also a feature of JPMN handlebars.

**Comment by bewizible** [comment]
@JonLuepf 

> have a frequency of 0 instead of 99999

not advised but you could use `{frequency-harmonic-occurrence}` for that

> I should raise these issues with the Yomitan developers instead maybe?

Does the dictionary name bother you that much? Maybe you could just write some css if you know how to and hide it

**Comment by JonLuepf** [comment]
> > I guess since Lapis just uses the Yomitan handlebars I should raise these issues with the Yomitan developers instead maybe?
> 
> Default Yomitan handlebar can totally do this. Use `{single-glossary-DICTIONARYNAME-brief}` in your anki template instead of what you currently have

Thanks, now I just have to edit the first line out of all my existing notes

**Comment by JonLuepf** [comment]
> > I guess since Lapis just uses the Yomitan handlebars I should raise these issues with the Yomitan developers instead maybe?
> 
> Default Yomitan handlebar can totally do this. Use `{single-glossary-DICTIONARYNAME-brief}` in your anki template instead of what you currently have
> 
> Now if you want to hide it from old cards though, You could add this to your style
> 
> ```css
> li[data-dictionary] i { display: none; }
> ```

Thanks, the yomitan handlebar does what I want. The css you sent does not work for me however.

**Comment by JonLuepf** [comment]
For me this css works:
`ol li[data-details="Jitendex.org [2024-09-16]"] .dict-group__tag-list {
  display: none;
}`

The only issue is that with this the "1." that was displayed in front of the first line drops below the definition. I think that is supposed to be the number of the dictionary. I am not sure why it is necessary for that to be even displayed because the main definition only has one dictionary anyway.

**Comment by JonLuepf** [comment]
The first CSS does not work for me, the second one does. Thank you
