### ISSUE TITLE
Would following the instructions to remove the "yomitan" tag remove the source tag too?

### ISSUE THREAD

**Issue by kimjongbing** [donkuri/lapis#4]
Would following the instructions to remove the "yomitan" tag remove the source tag too? How does the source tag work? Like if I'm watching X or Y anime or mining from X or Y visual novel, how is it getting the name? Or when it says manually do you mean like if I'm mining from something I should update the tag section myself?

Thank you

**Comment by bewizible** [comment]
@kimjongbing I would like to pipe in and just mention, for adding tags to your mined cards, you do not need any addons. Just a simple Ctrl+Shift+A would open the `Enter tags to add:` anki dialog.
