### ISSUE TITLE
Implement `DefinitionPicture` for Lapis

### ISSUE THREAD

**Issue by bewizible** [donkuri/lapis#5]
As the title says, we plan on adding a definition image field to Lapis. Using which, you can put in images for target word (vocab) you're trying to learn.

**Comment by phamthaison1207** [comment]
this would be highly beneficial for audiobooks and books mining cause they don't have any context besides the sentences for the ease of meaning absorption of new words.

**Comment by donkuri** [comment]
Personally I use covers and inner illustrations for books, but I didn't think about audiobooks.

**Comment by bewizible** [comment]
If i were to implement it, it'd be the same way JPMN did, UI-wise anyways, so say you have a card for 看板 mined from アマカノ２, you'd have that VN's image in the same place as always. Now what you could do is add an _extra_ image to describe the vocab you're trying to learn, 看板 in this case.
![ezgif-7-4326dd91e7](https://github.com/user-attachments/assets/e6fec9bc-edaa-4c73-bfd8-2c9fb1d156a3)

Now I'd say you don't really need an image for such an easy word, but how about words like 鶉 or 紫陽花? Do you think it'd be worth implementing something like this @donkuri

**Comment by donkuri** [comment]
I think that's a good idea yeah. Might be worth asking around if people would like that option implemented this way.

**Comment by Ceynou** [comment]
I guess it should be added to the README.md?

**Comment by donkuri** [comment]
@bewizible Any chance you could take care of it? I have important work coming up and I won't be available until next week.

**Comment by bewizible** [comment]
All right, mentioned it on the README. Thanks for waiting guys, I was really busy (and still am).
