### ISSUE TITLE
Implementation of auto-bolding target word in the sentence

### ISSUE THREAD

**Issue by SuncaLesinata** [donkuri/lapis#6]
As the title says, how hard would it be to implement this? i have combined more than one notetype and i am trying to "standardize" my deck with this note type. some cards have the target word bolded, other do not. thanks.

**Comment by donkuri** [comment]
Does this not already happen? Am I misunderstanding what you're asking?

**Comment by donkuri** [comment]
Ok I see I have misunderstood what you were asking for. I'm sorry, if other decks did not properly bold your target word, Lapis won't fix that. Either go through it manually or try to find a script that does this online. Good luck!

**Comment by SuncaLesinata** [comment]
Someone actually recommend me and anki addon that scans my "expression" field and then scans the "sentence" field to make the target word bolded so it solved the problem. https://ankiweb.net/shared/info/999501408

**Comment by donkuri** [comment]
Oh this looks great, thanks for sharing!
